# Generated by Django 3.2.3 on 2021-06-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('fathers_name', models.CharField(max_length=255)),
                ('phone1', models.CharField(max_length=30)),
                ('phone2', models.CharField(max_length=30)),
                ('phone3', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('more', models.CharField(max_length=255)),
            ],
        ),
    ]
