# Generated by Django 3.2.3 on 2021-05-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('fathers_name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('first_phone_number', models.CharField(max_length=20)),
                ('second_phone_number', models.CharField(max_length=20)),
                ('first_email', models.CharField(max_length=100)),
                ('second_email', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
                ('more', models.CharField(max_length=1000)),
            ],
        ),
    ]
