# Generated by Django 3.2.3 on 2021-06-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplebook',
            name='phone1',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='simplebook',
            name='phone2',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='simplebook',
            name='phone3',
            field=models.IntegerField(max_length=30),
        ),
    ]
