# Generated by Django 3.2.3 on 2021-05-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simple_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('e_mail', models.CharField(max_length=255)),
                ('more', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
