# Generated by Django 3.2.3 on 2021-05-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_simple_book_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='SimpleBook',
        ),
    ]
