# Generated by Django 3.2.3 on 2021-06-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20210612_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplebook',
            name='phone1',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='simplebook',
            name='phone2',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='simplebook',
            name='phone3',
            field=models.CharField(max_length=11),
        ),
    ]
