# Generated by Django 3.2.3 on 2021-06-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20210612_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplebook',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='simplebook',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='simplebook',
            name='email',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='simplebook',
            name='fathers_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='simplebook',
            name='first_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='simplebook',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='simplebook',
            name='more',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='simplebook',
            name='second_name',
            field=models.CharField(max_length=45),
        ),
    ]
